from enum import Enum


class OnboardingEmailCode(str, Enum):
    PRE_PAYMENT_REMINDER = "PRE_PAYMENT_REMINDER"
    ACCOUNT_SETUP_REMINDER = "ACCOUNT_SETUP_REMINDER"
    ALREADY_PAID_ONBOARDING = "ALREADY_PAID_ONBOARDING"
    CUSTOM_QUOTE_REQUEST = "CUSTOM_QUOTE_REQUEST"
    CUSTOM_QUOTE_PRICE_SUBMITTED = "CUSTOM_QUOTE_PRICE_SUBMITTED"
    PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION"


class EmailStatus(str, Enum):
    QUEUED = "QUEUED"
    SENT = "SENT"
    FAILED = "FAILED"
