"""remove-customquote-model

Revision ID: 42aa30157b9a
Revises: 20260223_add_payment_customer_id
Create Date: 2026-02-24 15:52:17.895157

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '42aa30157b9a'
down_revision = '20260223_add_payment_customer_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_quotes_email', table_name='custom_quotes')
    op.drop_index('ix_custom_quotes_id', table_name='custom_quotes')
    op.drop_table('custom_quotes')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_quotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='custom_quotes_pkey')
    )
    op.create_index('ix_custom_quotes_id', 'custom_quotes', ['id'], unique=False)
    op.create_index('ix_custom_quotes_email', 'custom_quotes', ['email'], unique=False)
    # ### end Alembic commands ###

