"""remove-customquote-model

Revision ID: 9e5f533f6efa
Revises: 42aa30157b9a
Create Date: 2026-02-24 18:55:39.781158

"""
from alembic import op
import sqlalchemy as sa



revision = '9e5f533f6efa'
down_revision = '42aa30157b9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

