"""add-price-id

Revision ID: f33d29b9cd8b
Revises: 20260224_merge_heads
Create Date: 2026-02-27 09:41:04.409568

"""
from alembic import op
import sqlalchemy as sa

revision = 'f33d29b9cd8b'
down_revision = '20260224_merge_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('price_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboarding_sessions', 'price_id')
    # ### end Alembic commands ###
