"""uuid_onboarding

Revision ID: 66e0e13a4fa3
Revises: 47eb4ce0ce6e
Create Date: 2026-02-05 13:20:31.989280

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '66e0e13a4fa3'
down_revision = '47eb4ce0ce6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add NOT NULL column with server_default to auto-generate UUIDs for existing rows
    op.add_column(
        'onboarding_sessions',
        sa.Column(
            'uuid',
            postgresql.UUID(as_uuid=True),
            nullable=False,
            server_default=sa.text("gen_random_uuid()")
        )
    )
    # Create unique index
    op.create_index(op.f('ix_onboarding_sessions_uuid'), 'onboarding_sessions', ['uuid'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_onboarding_sessions_uuid'), table_name='onboarding_sessions')
    op.drop_column('onboarding_sessions', 'uuid')
    # ### end Alembic commands ###

