"""add_custom_quote_submited

Revision ID: 35d2bf249f47
Revises: 20260213_rename_cq
Create Date: 2026-02-16 11:47:06.617281

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '35d2bf249f47'
down_revision = '20260213_rename_cq'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboarding_sessions', sa.Column('custom_quote_submitted', sa.Boolean(), server_default=sa.text('false'), nullable=False))


def downgrade() -> None:
    op.drop_column('onboarding_sessions', 'custom_quote_submitted')
    # ### end Alembic commands ###

