export const LICENSING_AGREEMENT = `**UNLIMITED VIDEO CONTENT LICENSING AGREEMENT**

**SUMMARY SHEET**

**THE PARTIES AGREE THAT THIS PAGE IS A SUMMARY OF THE AGREEMENT THAT FOLLOWS FOR LICENSEE'S CONVENIENCE, AND THE AGREEMENT THAT FOLLOWS CONTAINS THE FULL AND COMPLETE UNDERSTANDING OF THE PARTIES.**

| **TERM** | An annual (i.e. 12 month) Initial Period and annual Renewal Periods. |
| --- | --- |
| **FEES** | The Access Fee for the Initial Term and any Renewal Periods shall be the amount specified in the subscription plan or custom quote selected by the Licensee during the registration or checkout process. This fee is based on the number of Whitelisted Pages and/or audience size as indicated at the time of purchase. |
| **BILLING AND CANCELLATION** | You will be billed automatically unless cancelled at least 30 days prior to the end of the Initial Term or applicable Renewal Term by emailing BVIRAL at sales@bviral.com or as otherwise determined by BVIRAL. |
| **TERMINATION AND NO REFUND POLICY** | This license may only be terminated by BVIRAL in the event of your breach of the license terms in the Agreement. No refunds are available to you at any time unless otherwise stated in the Agreement. |
| **SPECIFIC BENEFITS** | • Watermark is not required. • Social media monetization is allowed. • Compilations are allowed. • Videos may not be used for ads/boosting. • Video editing is allowed. |
| **APPROVED PAGES ONLY** | You may submit your page(s) on Video distribution platforms for BVIRAL's approval, including on Facebook, Instagram, Snapchat, and YouTube. You cannot post Videos to any other pages other than the pages you whitelist with BVIRAL. |

*Strictly for reference; binding provisions are in the Agreement below.*

---

**UNLIMITED VIDEO CONTENT LICENSING AGREEMENT**

This content licensing agreement ("**Agreement**") is made between **________________** located at ________________ ("**Licensee**") and **Social Coaster Inc. d/b/a BVIRAL** located at 1441 New Hwy 96 W, Suite 2, # 120, Franklin, TN 37064 ("**Licensor**") and shall be effective upon ____________, 2026 (the "**Effective Date**"). Licensor and Licensee shall be individually referred to as a "**Party**" and collectively referred to as the "**Parties**". The Parties agree as follows:

**1. Term.** The term herein shall commence as of the Effective Date and expire on the One (1) year anniversary of the Effective Date (the "**Initial Term**"); provided, that this Agreement shall automatically renew for successive One (1) year periods (each, a "**Renewal Period**") unless Licensee provides written notice (email shall suffice) to sales@bviral.com (or another email designated by Licensor) at least 30 days prior to the end of the Initial Term or applicable Renewal Period, in which case this Agreement shall terminate at the end of the Initial Term or then current Renewal Period, as applicable (the Initial Term together with any Renewal Period(s), is collectively referred to as the "**Term**"). For the avoidance of doubt, Licensor shall have the right to terminate this Agreement at the end of the Initial Term or then current Renewal Period.

**2. Territory.** Worldwide (subject to any applicable use/territory restrictions, which use/territory restrictions shall be communicated in writing (email acceptable) by Licensor to Licensee from time to time).

**3. Publication of Video Content.**

a. Solely for the purposes herein and only during the Term, Licensee shall have access to (i) a library of videos now or hereafter owned or controlled by Licensor and its affiliated entities that are provided to Licensee via Licensor's content management system ("**Video(s)**"), and (ii) any other content that is owned or controlled by Licensor and provided to Licensee hereunder (such other content together with the Videos are collectively referred to herein as the "**Licensor Content**"). Subject to the terms and conditions herein, Licensee shall have the right to create videos by utilizing Licensor Content, which includes utilizing Videos or portion(s) of any Videos (each a "**Clip**") to create a compilation (i.e., a series of Videos and/or Clips), including in conjunction with Licensee's original content (i.e., content created by Licensee that does not include Licensor Content) ("**Derivative Video(s)**") subject to the terms and conditions of this Agreement. For the avoidance of doubt, during the Term, Licensee will have unlimited download credits to download Licensor Content from Licensor's designated content management portal.

b. For the purposes herein, short-form distribution platforms, pages and/or channels fully owned and operated by Licensee shall be referred to as "**Accounts**", which includes, but is not limited to, Accounts on Facebook, Instagram, Snapchat, and YouTube (collectively, the "**Platforms**"), where each publication of a Derivative Video and/or Clip on each Account on each Platform (each Account on each Platform referred to herein as a "**Page**") shall be referred to herein as a single "**Usage(s)**".

c. Upon Licensor's receipt of Licensee's information provided during the registration or checkout process (or Licensee's subsequent email to sales@bviral.com), Licensor will whitelist the approved Pages identified by the Licensee at the time of purchase (each a "Whitelisted Page"). Licensee may not reproduce, digitally transmit, perform, or exhibit any Usages via any accounts or pages other than the Whitelisted Pages unless Licensee obtains Licensor's prior written consent. In the event that Licensee publishes a Usage on a non-whitelisted Page, Licensor may promptly file a takedown and/or request removal. Licensee acknowledges that (i) they may only include Pages they fully own and operate and (ii) adding additional Whitelisted Pages after the initial checkout may require a new licensing agreement.

**4. Grant of Rights.**

a. During the Term, and solely as provided herein, Licensee shall have a non-exclusive license to edit, reproduce, digitally transmit, perform, exhibit, and publish Usages of Derivative Videos via Whitelisted Pages. Notwithstanding the foregoing, Licensee shall ensure that any and all Usages of the Licensor Content, including via Licensee's Derivative Videos, contain the required components to comply with the rules and regulations of each applicable distribution platform.

b. Licensor shall retain all rights, title, and interest in and to all Licensor Content and any and all derivate uses of the Licensor Content; provided, however, that Licensee may make a copy (including server copies) of the Licensor Content as necessary solely for purposes of enabling any permitted use under this Agreement hereunder.

c. Licensee grants to Licensor a perpetual, gratis, non-exclusive license to reproduce, edit, digitally transmit, perform, exhibit, and publish any portion of Licensee's Derivative Videos for marketing and promotional purposes. Licensee agrees and acknowledges that for any content that Licensee contributes to a particular Usage or Derivative Video (that is not Licensor Content), Licensee has the full rights and permission to use such content in each Usage or Derivative Video. Licensor shall not be responsible for any suspensions and/or penalties applied by any applicable Platforms as a result of Licensee's unauthorized Usages.

d. For the avoidance of doubt, (i) Licensee may enable Social Media Monetization on Whitelisted Pages in connection with Derivative Videos and (ii) Licensee shall not use such Derivative Videos as a Paid Advertisement on any Platforms. "Social Media Monetization" means the ability to generate advertising revenue from Usages on Platforms. "Paid Advertisement" means sponsored Usages that will be displayed to target audiences on Platforms.

**5. Licensor Content Fees.**

a. **Access Fees.** The Parties agree that in exchange for Licensee's access to the Licensor Content, Licensee shall pay to Licensor the Access Fee corresponding to the specific subscription plan or custom quote selected by the Licensee during the registration or checkout process. This initial Access Fee is due promptly upon the Effective Date. After the Initial Term, Licensee shall pay the applicable Access Fee promptly upon each Payment Due Date during the applicable Renewal Term. Licensee hereby authorizes Licensor to automatically charge Licensee's credit card or other payment method on file for recurring Access Fees in accordance with the terms herein. For the avoidance of doubt, Licensor will automatically charge Licensee the Access Fees promptly upon each Payment Due Date of the Initial Term and applicable Renewal Term unless the Agreement is otherwise terminated as provided herein.

b. **Late Payments.** Licensee agrees and acknowledges that Licensee shall pay each Access Fee to Licensor by each (i) One (1) month anniversary (or the next corresponding business day) of the beginning of the Initial Term and each applicable Renewal Term (if Licensee selects an Annual Subscription Option with monthly payments) or (ii) each One (1) year anniversary (or the next corresponding business day) of the beginning of the Initial Term and each applicable Renewal Term (if Licensee selects an Annual Subscription Option with annual payments) (the "**Payment Due Date**"). In the event that Licensee fails to pay (i) any applicable Access Fee to Licensor by the Payment Due Date during the Term, or (ii) in accordance with the payment method under this Section herein (each a "**Late Payment**"), Licensee will have no longer than five (5) days to cure such Late Payment. For each Late Payment to Licensor, Licensor (i) shall require Licensee to pay the applicable Access Fee, as well as the maximum interest allowed pursuant to relevant federal, state, and local laws and (ii) may immediately terminate Licensee's access to Licensor Content and Licensor's services to Licensee herein. Notwithstanding the foregoing, the first Access Fee is due to Licensor upon the Effective Date.

c. **No Refund Policy.** Licensee acknowledges that Licensor does not offer, and is not obligated to offer, refunds to Licensees for any Access Fees hereunder at any time. All Access Fees paid to Licensor are final. Licensee agrees that Licensee will not initiate a chargeback with its cardholder bank unless Licensee has first made a good faith effort to resolve any issues directly with Licensor. In the event Licensee initiates a chargeback without first attempting to resolve the issue with Licensor, Licensor may, at its sole discretion, refuse to provide any further services to Licensee. Licensor reserves the right to pursue legal action against Licensee in the event Licensee initiates any frivolous chargebacks.

**6. Licensor Content Delivery.** During the Term, Licensee may access all Licensor Content by accessing Licensor's digital asset management portal via the access credentials that Licensor provides to Licensee upon Licensee's payment of the first Access Fee and/or as otherwise specified by Licensor. Licensee agrees and acknowledges that Licensee shall only use Licensor Content downloaded from Licensor's digital asset management portal, as designated by Licensor.

**7. Licensor Content Use and Restrictions.** Licensee may edit the Videos to create Derivative Videos, provided that all right, title, and interest in and to the Licensor Content embodied in the Derivative Videos shall belong to Licensor. Licensee may alter Licensor Content to insert identification data (e.g., credits and handles), promotional graphics or images (e.g., overlays), sponsorships, advertising, ratings information, closed captioning, and such other data as Licensor may require provided that any promotions or advertisements shall not imply any endorsement of or affiliation with a product or service by Licensor or any of its content owners. Licensee shall have the right to modify the technical and visual format of the Licensor Content as necessary to enable the Usages to be transmitted via a Page, including, without limitation, to comply with each Platform's content guidelines. Licensee must use the Licensor Content in accordance with any and all applicable local, state, and federal laws, and may not be used with or within a production involving promotion or exploitation of illegal affairs. Licensee agrees to use reasonable efforts to tag or credit the original video owner on Instagram posts (as provided by Licensor). Notwithstanding the foregoing, the Usages of Licensor Content (including via Licensee's Derivative Videos) shall only be used by Licensee to post to approved Platform(s) (i.e., Facebook, Instagram, YouTube, Snapchat). In the event Licensor notifies Licensee in writing (email shall suffice) that any Licensor Content and/or Derivative Videos need to be removed from any of Licensee's Pages, Licensee shall promptly remove such Licensor Content and/or Derivative Videos within two (2) business days of such notice.

**8. Music Limitations.** Licensee shall be responsible, at its sole cost, for securing all rights, permissions, clearances, and licenses necessary for Licensee and the Pages to distribute, transmit, display, publicly perform, exhibit and promote Usages of Licensor Content (including via Licensee's Derivative Videos) as required for use of the musical compositions or sound recordings owned by third parties used in accordance with the terms of the Agreement, including, but not limited to, securing any licenses (e.g., ASCAP/BMI/SESAC) for the public use of these sounds and/or music or Licensee shall remove and replace the music and sounds owned by third-party rights holders. In the event Licensee is not able to procure the proper license(s) associated with a particular musical composition and/or sound recording used in connection with Licensor Content (including via Licensee's Derivative Videos) Licensee agrees and acknowledges that Licensee must replace the sound recording or musical composition with music/copyrights for which Licensee own the rights to.

**9. Termination.** The Parties agree and acknowledge that the Term of this Agreement may only terminate in accordance with Section 1 herein; provided, however that, in the event Licensee commits a material breach of this Agreement, including, but not limited to Licensee's unauthorized use of Licensor Content, Licensee agrees that Licensor shall be entitled to terminate this Agreement, require Licensee to immediately remove any Licensor Content and/or Derivative Videos from all Pages, seek injunctive and other equitable relief to prevent and/or cure any breach or threatened breach of this Agreement by Licensee without any refund to Licensee. Further, Licensor shall not be prohibited from pursuing all other remedies, including monetary damages for loss and damages. For the avoidance of doubt, Licensee agrees and acknowledges that Licensee shall not re-post, cross-post, or publish any Licensor Content, including, in the form of a Derivative Video, or any other form on any Page upon expiration of the Term of this Agreement.

**10. Usage Reporting Required.** Licensee agrees and acknowledges that Licensee may be required to report certain Usage metrics to Licensor with regards to the Licensor Content or Derivative Videos. Notwithstanding the foregoing, in the event that Licensee fails to notify Licensor that Licensee published a Usage on a Page that is not a Whitelisted Page, Licensor may require Licensee to pay the applicable Access Fees, as well as the maximum interest allowed pursuant to relevant federal, state, and local laws for such use.

**11. Representations and Warranties.** Each Party represents and warrants to the other that it has the power and authority to enter into this Agreement and to fully perform all of its obligations hereunder. Licensee further represents and warrants that Licensee (i) has not been misled or deceived by any statement or omission made by Licensor, its agents, or representatives, in connection with this Agreement; (ii) has read this Agreement and Licensee is not relying on any statement or omission made by Licensor, its agents, or representatives, that is not expressly set forth in this Agreement; (iii) owns and/or controls the Pages and content contributed in the Derivative Videos as required to make each grant of right set forth herein and to comply with its obligations hereunder; (iv) the Pages and the content contributed in the Derivative Videos shall not violate or infringe on the rights of any third party; (v) the exercise by Licensee of the rights granted to it by Licensor under this Agreement will not cause any monies or other consideration to be due to any third party by Licensee that is not expressly set forth in this Agreement; and (vi) Licensee understands that this Agreement is available to individual licensees (which shall only include individuals, sole proprietors, small businesses that are individually owned), corporations, and limited liability companies.

**12. Indemnification.** Licensee and Licensor shall each indemnify, defend, and hold harmless the other from and against any and all claims, losses, damages, costs and expenses (including reasonable counsel fees) (collectively, "**Liabilities**") to the extent arising out of any breach or claimed breach of any of its representations or warranties or any of its obligations pursuant to this Agreement. In any case in which indemnification is sought, the indemnified party shall (i) promptly notify the indemnifying party of the claim (provided that the failure to do so shall not relieve the indemnifying party of its obligations hereunder except to the extent such failure to notify materially prejudices the indemnifying party), and (ii) afford the indemnifying party the opportunity of defending such claim and controlling the litigation, settlement or other disposition of such claim (provided that any settlement shall require the indemnified party's consent unless the settlement relates solely to the indemnifying party's payment of money damages [i.e., the settlement imposes no obligations or admissions on the indemnified party]). If the indemnifying party does not elect to defend such claim, then indemnified party may do so at the indemnifying party's sole expense. The indemnified party may otherwise participate in any such action with its own counsel at its expense.

**13. Limitation of Liability.** THE VIDEOS AND LICENSOR CONTENT ARE LICENSED "AS IS" AND THERE ARE NO WARRANTIES, CLAIMS, OR REPRESENTATIONS MADE BY LICENSOR EITHER EXPRESS, IMPLIED, OR STATUTORY, WITH RESPECT TO THE VIDEOS AND LICENSOR CONTENT, INCLUDING WARRANTIES OF QUALITY, PERFORMANCE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE, NOR ARE THERE ANY WARRANTIES CREATED BY COURSE OF DEALING, COURSE OF PERFORMANCE, OR TRADE USAGE. LICENSOR DOES NOT WARRANT THAT THE VIDEOS AND LICENSOR CONTENT WILL MEET LICENSEE'S NEEDS OR BE FREE FROM ERRORS, THAT THE OPERATION OF THE LICENSOR CONTENT AND DELIVERABLES WILL BE UNINTERRUPTED, AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE VIDEOS AND LICENSOR CONTENT, OR AS TO THE ACCURACY, RELIABILITY, OR CONTENT OF ANY INFORMATION OR PRODUCTS PROVIDED THROUGH THE VIDEOS AND LICENSOR CONTENT. THE FOREGOING EXCLUSIONS AND DISCLAIMERS ARE AN ESSENTIAL PART OF THIS AGREEMENT AND FORMED THE BASIS FOR DETERMINING THE ACCESS FEES HEREIN.

**14. Disclaimer.** LICENSEE UNDERSTANDS AND AGREES THAT LICENSOR IS NOT RESPONSIBLE FOR ANY STATEMENTS OR REPRESENTATIONS REGARDING LICENSOR'S PRODUCTS AND/OR SERVICES MADE BY ANY THIRD PARTY, INCLUDING BUT NOT LIMITED TO, CONTENT CREATORS, AFFILIATES, AND/OR OTHER USERS OF LICENSOR'S PRODUCTS AND/OR SERVICES. LICENSOR DOES NOT CONTROL, ENDORSE, OR ADOPT ANY SUCH STATEMENTS OR REPRESENTATIONS. LICENSEE AGREES AND ACKNOWLEDGES THAT ANY RELIANCE ON ANY SUCH STATEMENTS OR REPRESENTATIONS IS SOLELY AT LICENSEE'S OWN RISK. LICENSEE ACKNOWLEDGES AND AGREES THAT LICENSOR AND/OR LICENSOR'S PRODUCTS AND/OR SERVICES ARE USED IN CONNECTION WITH AN AFFILIATE PARTICIPATING IN LICENSOR'S AFFILIATE PROGRAM, WHEREBY SUCH AFFILIATE MAY BE RECEIVING A COMMISSION AND/OR COMPENSATION FROM LICENSOR. FURTHER, LICENSOR IS NOT RESPONSIBLE FOR THE ACTIONS OR REPRESENTATIONS OF SUCH AFFILIATE.

**15. Force Majeure.** Notwithstanding any other provision herein, no party shall be liable for any failure to perform its obligations hereunder (excluding payment obligations that are due and payable) resulting from any war, labor dispute, fire, flood, riot, acts of God or any other cause beyond its reasonable control.

**16. Notice.** All notices hereunder shall be in writing. All notices to Licensor hereunder shall be delivered by personal delivery, express courier (e.g., federal express), or via e-mail to:

Jonathan Burdon  
1441 New Hwy 96 W  
Suite 2, # 120  
Franklin, TN 37064  
Jonathan@bviral.com

with a copy to: Buchalter, PC  
Attn: Lauren Spahn  
1 Music Circle South, Suite 300  
Nashville, TN 37203  
lspahn@buchalter.com

All notices to Licensee hereunder shall be delivered by personal delivery, express courier, or via e-mail to the address provided during registration.

**17. Breach/Cure.** In the event Licensee breaches this Agreement, then Licensor may provide written notice to Licensee (email shall suffice) of such breach, and Licensee shall have a period of ten (10) days (5 days for Late Payments to Licensor) (the "**Cure Period**") to cure such breach. Notwithstanding the foregoing, if Licensee selects an Annual Subscription Option and fails to cure such breach within the Cure Period, Licensee shall promptly (i) remove any Licensor Content and/or Derivative Videos from all Pages promptly upon the expiration of the Cure Period and (ii) pay any remaining Access Fees that are due for the remainder of the Term as set forth herein.

**18. Assignment.** Licensee shall not assign, transfer, or sublicense this Agreement or its rights to the Licensor Content granted herein, directly, or indirectly, by operation of law or otherwise, without the express written consent of Licensor. Licensor shall be entitled to freely assign this Agreement in Licensor's sole discretion.

**19. Confidentiality.** Neither Party shall disclose the terms of this Agreement or any other information (oral or written) regarding the business and affairs of the other party to any person or entity without the disclosing party's prior written consent, except (a) to the receiving party's parent companies, auditors and attorneys as part of its normal reporting and review procedure; provided, that any such persons agree to be bound by these confidentiality terms; (b) to the extent necessary to comply with law or a discovery request in any legal proceeding (provided the receiving party provides the disclosing party with prompt advance written notice (before disclosure) of any such proposed disclosure and seeks confidential treatment of such information) and (c) to the extent such information is already in the public domain through no fault of the receiving party. As used herein, "disclosing party" means the party furnishing confidential information and "receiving party" means the Party receiving it.

**20. Governing Law.** This Agreement and the rights and obligations of the Parties hereunder shall be governed by and construed in accordance with the laws of the State of Tennessee applicable to contracts entered into and fully performed therein, and each party consents to the exclusive jurisdiction of the state and federal courts (i.e. U.S. District Court for the Middle District) located in Davidson County, Tennessee and any appellate court from any thereof, for the adjudication of any claims or disputes arising out of or related to this Agreement. In the event of any action, suit or proceeding arising from or based upon this Agreement brought by either party hereto against the other, the prevailing party shall be entitled to recover from the other its attorneys' fees reasonably incurred in connection therewith in addition to the costs of that action, suit or proceeding.

**21. Privacy Policy.** Licensee agrees to be bound to Licensor's Privacy Policy and Licensor may adjust such Privacy Policy and/or at any time, in Licensor's sole discretion. Such Privacy Policy can be found at: https://bviral.com/privacy-policy/

**22. Miscellaneous.** This Agreement, including all schedules, exhibits and attachments hereto, constitutes the entire understanding and agreement between the Parties with respect to the subject matter hereof and supersedes all prior and contemporaneous understandings between the Parties, whether oral or written. Any modification or amendment of this Agreement must be in writing and signed by both Parties. This paragraph, including sections 6, 7, 8, 10, 11, 12, 13, 14, 16, 18, 19, 20, 21 and 22, of this Agreement, shall survive any termination or expiration of this Agreement. This Agreement may be signed in one or more counterparts, each of which shall be deemed to be an original, and all of which, when taken together, shall constitute but one and the same instrument.

---

**IN WITNESS WHEREOF**, the Parties have caused this Agreement to be executed as of the Effective Date.

**AGREED AND ACCEPTED:**

**LICENSOR:**  
SOCIAL COASTER INC. d/b/a BVIRAL

![Authorized Signature](/images/signature.png)

An Authorized Representative

**LICENSEE:**  
By typing your name below, you agree to the terms above and authorize payment.
`;
